const USERNAME_MIN_LENGTH = 3
const USERNAME_MAX_LENGTH = 15
const PLAYERS_MIN_NUMBER = 3
const PLAYERS_MAX_NUMBER = Infinity

module.exports = {
  USERNAME_MIN_LENGTH,
  USERNAME_MAX_LENGTH,
  PLAYERS_MIN_NUMBER,
  PLAYERS_MAX_NUMBER,
}
